name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
#   format:
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: apps/matching-engine
#     steps:
#       - uses: actions/checkout@v3
#       - uses: dtolnay/rust-toolchain@stable
#       - uses: mbrobbel/rustfmt-check@master
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: KengoTODA/actions-setup-docker-compose@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/apps/matching-engine
    steps:
    - uses: actions/checkout@v3
    - name: Set up Redis Instance with Docker
      working-directory: ${{ github.workspace }}
      run: docker-compose -f "docker-compose.yml" up -d --build
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down
